nhn/tui.calendar

src/js/view/month/more.hbs

Apply the `allday` template function on more layer in monthly view.
---

feat: Apply the allday template (close #5)

---

examples/css/default.css
src/css/month.styl
src/js/factory/monthView.js
src/js/view/month/more.js

The bootstrap of demo affected this.
close button's position has changed.
---

fix: Width error of month more layer (fix: #10)

---

package-lock.json
package.json
test/.eslintrc
test/app/common/ajax.spec.js
test/app/common/dw.spec.js
test/app/common/floatingLayer.spec.js
test/app/common/timezone.spec.js
test/app/common/vlayout.spec.js
test/app/common/vpanel.spec.js
test/app/controller/viewMixin/core.spec.js
test/app/controller/viewMixin/month.spec.js
test/app/factory/calendar.spec.js
test/app/handler/allday/click.spec.js
test/app/handler/allday/moveGuide.spec.js
test/app/handler/allday/resize.spec.js
test/app/handler/allday/resizeGuide.spec.js
test/app/handler/milestone/click.spec.js
test/app/handler/month/core.spec.js
test/app/handler/month/guide.spec.js
test/app/handler/month/resize.spec.js
test/app/handler/task/click.spec.js
test/app/handler/time/click.spec.js
test/app/handler/time/creationGuide.spec.js
test/app/view/taskview.spec.js
test/app/view/weekday.spec.js
test/app/view/weekdayInMonth.spec.js
test/matcher/matrices.js
test/matcher/timezone.js

Use `eslint-plugin-jasmine`.
Use globals: `fixture`, `underscore`
---

fix: eslint error for test source code (fix #13)

---

test/app/common/vlayout.spec.js
test/app/handler/allday/click.spec.js
test/app/handler/milestone/click.spec.js
test/app/handler/time/click.spec.js
test/app/view/taskview.spec.js

fix: missing files(eslint error fixes)

---

src/js/common/timezone.js
src/js/factory/calendar.js

PST(-08:00) in USA should properly be changed PDT(-07:00) based on summer time.
The summer time duration is from 2nd Sunday March to last Sunday November.
---

fix: summer time issue(DST)

---

examples/js/default.js
src/js/common/vlayout.js
src/js/common/vpanel.js
src/js/factory/calendar.js
src/js/factory/weekView.js

Add `Calendar.toggleScheduleView()` to show and hide 'AllDay', 'TimeGrid' panels and additional  `options.scheduleView` flag(similar to `options.taskView`) when initializing Calendar.
`VLayout` manages views to layout vertical views 'Milestone', 'Task', 'AllDay', 'TimeGrid'.
Panel array to contain view's height and sequence information had been managed by array index, but it was hard to use. So It has changed and beed managed by view's name as a key.
---

feat: show only milestone, task view (close #22)

---

.eslintrc
examples/css/default.css
examples/js/default.js
src/css/week/allday.styl
src/css/weekday.styl
src/js/common/datetime.js
src/js/common/vlayout.js
src/js/factory/weekView.js
src/js/handler/allday/click.js
src/js/handler/allday/creation.js
src/js/handler/allday/creationGuide.js
src/js/handler/month/click.js
src/js/handler/month/creation.js
src/js/view/month/weekdayInMonth.hbs
src/js/view/month/weekdayInMonth.js
src/js/view/template/helper.js
src/js/view/template/week/allday.hbs
src/js/view/week/allday.js
src/js/view/week/week.js
src/js/view/week/weekdayInWeek.hbs
src/js/view/week/weekdayInWeek.js
src/js/view/weekday.js
test/app/datetime.spec.js
test/app/handler/allday/click.spec.js
test/app/handler/allday/creation.spec.js
test/app/handler/time/creationGuide.spec.js

Feat: add "expandable and collapsable" view type to allday panel (closes #27)

---

src/js/view/week/weekdayInWeek.hbs
src/js/view/week/weekdayInWeek.js

fix handlebars if condition expression.
---

fix: some all-day schedule is rendered using task template (fix #40)

---

src/js/factory/weekView.js
src/js/view/week/allday.js
src/js/view/week/weekdayInWeek.js

fix: default height of task panel is too wide (fixes: #42)

---

examples/js/default.js
src/css/weekday.styl
src/js/common/vpanel.js
src/js/factory/weekView.js
src/js/handler/allday/click.js
src/js/handler/allday/creation.js
src/js/view/month/weekdayInMonth.js
src/js/view/template/week/allday.hbs
src/js/view/week/allday.js
src/js/view/week/weekdayInWeek.hbs
src/js/view/week/weekdayInWeek.js
src/js/view/weekday.js
test/app/handler/allday/click.spec.js
test/app/handler/allday/creation.spec.js
test/app/view/weekdayInMonth.spec.js

feat: add toggle button at all-day panel (closes: #27)

---

src/js/factory/weekView.js
src/js/handler/allday/click.js
src/js/view/week/weekdayInWeek.hbs
src/js/view/week/weekdayInWeek.js
test/app/handler/allday/click.spec.js

hotfix: change toggle view's collapse button spec (refs: #27)

---

src/js/common/datetime.js
src/js/view/month/weekdayInMonth.js

fix: weekday exceed date calculation bug in month view

---

src/js/handler/allday/click.js

fix: allday schedule click event not working when no collapse button

---

src/js/common/common.js
src/js/factory/calendar.js
src/js/view/month/month.js
src/js/view/month/weekdayInMonth.js
src/js/view/week/time.js
src/js/view/week/timeGrid.js

**100% enhancement in monthly view approximately.**
**10% enhancement in weekly view approximately.**
Removed three `force layout` with prevent or reduce getting element size.
Reduced consecutive render() function execution. The last calling it will be executed.
(ex> 3 times render() -> 1 time render())
---

perf: enhance Calendar.render() performance (close #34)

---

examples/css/default.css
examples/example01-basic.html

- [-] Tests for the changes have been added (for bug fixes/features) 
- [-] Docs have been added/updated (for bug fixes/features)
---

chore: fix logo image path and add cursor on lnb list

---

examples/js/default.js
src/js/factory/calendar.js
src/js/factory/monthView.js
src/js/factory/weekView.js
src/js/handler/daygrid/core.js
src/js/handler/daygrid/creation.js
src/js/handler/month/creation.js
src/js/handler/month/guide.js
src/js/handler/time/core.js
src/js/handler/time/creation.js
src/js/handler/time/creationGuide.js

feat: add an api openCreationPopup()

---

examples/css/default.css
examples/css/icons.css
examples/example01-basic.html
examples/js/default.js
src/css/popup.styl
src/js/view/popup/scheduleCreationPopup.js
src/js/view/popup/scheduleDetailPopup.js
src/js/view/template/popup/scheduleCreationPopup.hbs
src/js/view/template/popup/scheduleDetailPopup.hbs
test/app/view/scheduleCreationPopup.spec.js

Add prefix to common classname like `icon` or `content`
http://10.78.9.237:8080/examples/example01-basic.html
---

refactor: add prefix to classname `icon, content`

---

examples/js/theme/dooray.js
src/js/factory/calendar.js
src/js/theme/standard.js
src/js/theme/theme.js
src/js/theme/themeConfig.js
test/fixtures/theme-dooray.json

Re render the calendar after `Calendar.setTheme()`.
Add (fallback)default theme styles.
---

fix: default theme styles and re-render it

---

CONTRIBUTING.md

I added the word "to" to a sentence in the contributing text.
---

Update and fix a typo in Contributing.md

---

src/js/factory/calendar.js
src/js/factory/weekView.js

feat: Add an Option to disable "all day" view (close #93)

---

src/js/common/common.js
src/js/factory/monthView.js
src/js/factory/weekView.js
src/js/view/popup/scheduleCreationPopup.js
src/js/view/week/dayGrid.js

#87 and Remove `Array.find()`.
---

fix: Erros for IE.

---

src/js/view/popup/scheduleDetailPopup.js

Because of duplicate `id`.
---

fix: Default popup's arrow position error (close #74)

---

examples/js/default.js
src/js/factory/calendar.js
src/js/factory/monthView.js
src/js/view/month/month.js
src/js/view/week/week.js

feat: Add new event `afterRenderSchedule` (close #109)

---

examples/js/theme/dooray.js
src/js/theme/standard.js
src/js/theme/themeConfig.js
src/js/view/template/week/timeGrid.hbs
src/js/view/week/timeGrid.js

This feature's sample image is
**It's only for today in daily and weekly**.
---

 feat: Add a theme for time display text in weekly

---

karma.conf.js
package-lock.json
package.json
test/app/common/array.spec.js
test/app/common/vlayout.spec.js

chore: testcase, remove `underscore` pluck (close #114)

---

README.md

I strengthened the style of a couple of titles in the readme file.  I attempted to update the hashtag links, too.  I hope they still work.
---

Doc: Strengthened the language style

---

examples/js/theme/dooray.js
src/css/week/time.styl
src/js/theme/standard.js
src/js/theme/themeConfig.js
src/js/view/template/week/timeGrid.hbs
src/js/view/template/week/timezoneSticky.hbs
src/js/view/week/dayname.js
src/js/view/week/timeGrid.js
test/app/view/timeGrid.spec.js

Apply the timezone display styles by dooray design.
---

feat: Add ability to display last time in different color

---

src/js/common/dw.js

When moving to other month there was a mis-calculating month and day.
---

fix: move month logic

---

README.md
src/js/factory/calendar.js
src/js/view/popup/scheduleCreationPopup.js
src/js/view/template/popup/scheduleCreationPopup.hbs

fix: dropdown menu arrow icon makes scrollbar at IE9 (resolves: #50)

---

README.md
src/index.js

Add a jquery plugin for tui-calendar
---

feat: Add jquery plugin `tuiCalendar`

---

src/js/factory/calendar.js

fix: setCalendarColor error with option.calendars

---

docs/getting-started.md
src/js/factory/calendar.js
src/js/factory/monthView.js
src/js/factory/weekView.js
src/js/view/month/month.js
src/js/view/month/weekdayInMonth.js
src/js/view/template/month/weekdayInMonthSchedule.hbs
src/js/view/template/week/dayGridSchedule.hbs
src/js/view/week/dayGrid.js
src/js/view/week/dayGridSchedule.js
src/js/view/week/time.js
src/js/view/week/timeGrid.js

feat: Support isReadOnly option of Calendar (close #164)

---

README.md

Replace url `https://nhnent.github.io/tui.calendar/latest` to `https://nhnent.github.io/tui.calendar/latest/Calendar.html`
---

docs: fix `APIs` link

---

src/index.js

Minor change for using jQuery global.
---

style: jQuery global (fix #180)

---

docs/getting-started.md
examples/js/default.js
src/js/factory/calendar.js
src/js/factory/monthView.js
src/js/view/month/more.js

Add a new callback `clickMore` for showing up more view in monthly.
---

feat: Add 'clickMore' callback in monthly view (close #170)

---

src/js/view/template/popup/scheduleDetailPopup.hbs

feat: Don't show state(busy/free) if undefined (close #182)

---

README.md

Add document usage statistics.
---

doc: Add document usage statistics (close #172)

---

src/js/controller/base.js

options.isAllDay is boolean type. not only options.isAllDay is not undefined but also options.isAllDay if false it's schedule is not seted
so, it can't uncheck allday check and time #211
---

fix: Wrong undefined validation expression

---

src/js/factory/calendar.js
src/js/theme/themeConfig.js

feat: change annotations for typedef object description (close #220)

---

examples/js/default.js
index.d.ts
src/js/factory/calendar.js
src/js/view/template/helper.js
src/js/view/template/week/timeGrid.hbs
src/js/view/template/week/timeGridCurrentTime.hbs
src/js/view/week/timeGrid.js

* current time template in timegrid(weekly view, daily view)
```js
// Usage
cal = new Calendar('#calendar', {
defaultView: 'week',
...
template: {
...
timegridCurrentTime: function(timezone) {
var diffDates = '';
var currentHour = moment(timezone.hourmarker.toUTCString());
if (timezone.dateDifference) {
diffDates = '(' + timezone.dateDifferenceSign + timezone.dateDifference + ')<br>';
}
return [
diffDates,
currentHour.format('HH:mm a')
].join('');
}
},
timezones: [
{
timezoneOffset: 540,
displayLabel: 'GMT+09:00',
tooltip: 'Seoul'
},
{
timezoneOffset: -420,
displayLabel: 'GMT-08:00',
tooltip: 'Los Angeles'
}
]
});
```
---

feat: support new current time template (close #286)

---

examples/js/app.js
src/js/view/month/more.js

* Modify that the More View of the last row and column is displayed correctly in a monthly view.
---

fix: change more view position in monthly view (fix #300)

---

CONTRIBUTING.md
docs/README.md
docs/getting-started-with-bower.md
docs/getting-started.md
examples/example00-basic.html
jsdoc.conf.json
package-lock.json
package.json
src/js/factory/calendar.js
tuidoc.config.json

chore: rename 'nhn'

---

examples/example15-template-for-timegrid.html
src/js/factory/calendar.js
src/js/view/template/helper.js
src/js/view/template/week/timeGrid.hbs

fix: breaking change for timegridDisplayPrimayTime

---

src/js/view/template/helper.js

Fix script `this` error.
Refer to
https://github.com/nhn/tui.calendar/commit/76b1ac6a3adf02b60d1381c29398a0d847cd6a9b#commitcomment-33238514
---

fix: error for timegridDisplayPrimayTime

---

src/js/view/month/more.js

fix : fix ui broken more view on monthly view

---

index.d.ts
src/js/factory/calendar.js
test/types/type-tests.ts

Fix a type definition error(boolean -> number)
---

fix: Wrong type for IMonthOptions.visibleWeeksCount (close #307)

---

examples/example15-template-for-timegrid.html
src/js/view/template/helper.js

fix : Show wrong midday(12 am => 12 pm) on time grid primary time (fix #321)

---

README.md

README의 used by 섹션에 회사명을 추가합니다
---

docs: update to the used by section of the readme

---

src/js/factory/calendar.js
src/js/factory/monthView.js
src/js/factory/weekView.js
src/js/view/popup/scheduleCreationPopup.js

fix : resolve tracking GA option inside using tui component

---

README.md

docs: update used by

---

README.md
docs/getting-started-with-bower.md
docs/getting-started.md

docs: import css dependencies

---

src/js/common/datetime.js

* Changes 00:00pm to 12:00pm in detail popup
AS-IS
TO-BE
---

fix: changes 00:00pm to 12:00pm in view popup (close #296)

---

src/js/factory/calendar.js

fix: disable workweek option in day view

---

examples/duplicate-schedule-layout-01.html
src/js/view/week/time.js

feat: imporvement duplicate main schdeule style

---

src/js/view/template/month/more.hbs

* fix: add semicolon for custom style on more view schedule
---

fix: add semicolon for custom style on more view schedule

---

README.md
docs/getting-started-with-bower.md
examples/example00-basic.html
examples/example01-monthly.html
examples/example02-weekly.html
examples/example03-daily.html
examples/example04-2-weeks.html
examples/example05-3-weeks.html
examples/example06-narrow-weekends.html
examples/example07-hide-weekends.html
examples/example08-task-n-schedule.html
examples/example09-task-only.html
examples/example10-common-theme.html
examples/example11-monthly-theme.html
examples/example12-weekly-theme.html
examples/example13-timezone.html
examples/example14-template-for-month.html
examples/example15-template-for-timegrid.html
examples/example16-template-for-popup.html

* add dependency tui-dom for cdn example pages.
---

fix : add cdn dependency tui-dom (fix #376)

---

README.md
docs/getting-started-with-bower.md
docs/getting-started.md

* reorder contents for README.md file 
---

chore: reorder README.md contents

---

src/js/view/template/popup/scheduleCreationPopup.hbs
src/js/view/template/popup/scheduleDetailPopup.hbs
src/js/view/template/week/dayGrid.hbs

* Modify html code to be parsed in templates
---

fix: can use html text for templates (fix #380)

---

README.md

chore: fix Wrappers link on README.md

---

examples/duplicate-schedule-layout-01.html
examples/example00-basic.html
examples/example01-monthly.html
examples/example02-weekly.html
examples/example03-daily.html
examples/example04-2-weeks.html
examples/example05-3-weeks.html
examples/example06-narrow-weekends.html
examples/example07-hide-weekends.html
examples/example08-task-n-schedule.html
examples/example09-task-only.html
examples/example10-common-theme.html
examples/example11-monthly-theme.html
examples/example12-weekly-theme.html
examples/example13-timezone.html
examples/example14-template-for-month.html
examples/example15-template-for-timegrid.html
examples/example16-template-for-popup.html
examples/js/data/calendars.js

* 예제 HTML파일에 tui-dom CDN 링크 추가
* 예제용 캘린더 리스트 만드는 부분 리팩토링
---

Fix : add tui dom cdn links and Refactor: generate Calendar List for demo

---

examples/duplicate-schedule-layout-01.html
examples/js/data/duplicate-schedules.js

chore : update example for duplicate schedule

---

examples/example00-basic.html
examples/example01-monthly.html
examples/example02-weekly.html
examples/example03-daily.html
examples/example04-2-weeks.html
examples/example05-3-weeks.html
examples/example06-narrow-weekends.html
examples/example07-hide-weekends.html
examples/example08-task-n-schedule.html
examples/example09-task-only.html
examples/example10-common-theme.html
examples/example11-monthly-theme.html
examples/example12-weekly-theme.html
examples/example13-timezone.html
examples/example14-template-for-month.html
examples/example15-template-for-timegrid.html
examples/example16-template-for-popup.html

closing tags link are not needed
---

fix: remove not needed closing tags

---

README.md
package-lock.json
package.json

* resolve security vulnerabilities about dependency packages.
* fix npm audit
---

fix: resolve security vulnerabilities for npm audit(resolve #405)

---

examples/example00-basic.html
examples/example01-monthly.html
examples/example02-weekly.html
examples/example03-daily.html
examples/example04-2-weeks.html
examples/example05-3-weeks.html
examples/example06-narrow-weekends.html
examples/example07-hide-weekends.html
examples/example08-task-n-schedule.html
examples/example09-task-only.html
examples/example10-common-theme.html
examples/example11-monthly-theme.html
examples/example12-weekly-theme.html
examples/example13-timezone.html
examples/example14-template-for-month.html
examples/example15-template-for-timegrid.html
examples/example16-template-for-popup.html

* remove script type attribute(default: test/javascript in html5 document)
* remove slash on link tag(do not need to `/`(*slash*) before closing the tag. Used in xhtml) 
---

chore: refactor example html files

---

src/js/view/week/dayGrid.js
src/js/view/week/dayname.js
src/js/view/weekday.js

Fixed the issue of incorrect display of today in weekly, monthly and daily views
* Fixed the issue of incorrect display of today in weekly, monthly and daily views
---

fix : #Dooray-Calendar/1119 : Fixed the issue of incorrect display of today in weekly, monthly and daily views

---

src/js/view/week/dayGrid.js
src/js/view/week/dayname.js
src/js/view/weekday.js

* Fixed the issue of incorrect display of today in weekly, monthly and daily views
---

fix: when changing timzone, today display issue(fix #416)

---

.gitignore
.vscode/settings.json
karma.conf.js
package.json
src/ts/base.ts
src/ts/calendar.ts
src/ts/model/index.ts
src/ts/model/schedule.ts
src/ts/model/scheduleViewModel.ts
src/ts/theme/index.ts
src/ts/theme/preset.ts
src/ts/theme/themeProps.ts
src/ts/time/date.ts
src/ts/time/datetime.ts
src/ts/util/index.ts
test-ts/model/schedule.spec.ts
test-ts/time/date.spec.ts
test-ts/time/datetime.spec.ts
tsconfig.es6.json
tsconfig.esm.json
tsconfig.json
types/tui-code-snippet.d.ts

The folder model/theme/time are converted to typescript. The related test cases are too.
---

[v2.0] convert js to ts

---

src/js/factory/calendar.js

fix: overwrite schedule color only if not customized (fix #437)

---

src/ts/controller/base.ts
src/ts/controller/month.ts
src/ts/controller/week.ts
src/ts/factory/calendarControl.tsx
src/ts/model/index.ts
test-ts/app/controller/base.spec.ts
test-ts/app/controller/month.spec.ts
test-ts/app/controller/week.spec.ts

Base.ts
Remove ModelController class and separate model and base controller class.
---

refactor: separate model and base controller

---

.storybook/webpack.config.js
karma.conf.js
package-lock.json
package.json
src/ts/components/template.tsx
src/ts/components/timeSchedule.tsx
src/ts/controller/base.ts
src/ts/controller/month.ts
src/ts/controller/week.ts
src/ts/factory/calendarControl.tsx
src/ts/model/index.ts
src/ts/template/default.ts
src/ts/template/index.ts
src/ts/util/cssHelper.ts
src/ts/util/index.ts
src/ts/view/monthView.tsx
stories/scheduleBlock.stories.tsx
test-ts/app/controller/base.spec.ts
test-ts/app/controller/month.spec.ts
test-ts/app/controller/week.spec.ts
test-ts/app/template/template.spec.tsx
test-ts/app/theme/theme.spec.ts
test-ts/app/util/array.spec.ts
test-ts/app/util/cssHelper.spec.ts
tsconfig.json
types/preact-context-provider.d.ts

* add sample timeSchedule component for storybook test
Add template html feature to v2.0.
Add a story for template html feature(timeSchedule.tsx)
Add a package `preact-context-provider` for test and storybook to inject a context.
Refactor eslint 2 error(findByDateRange method max-params)
---

feat: [v2] add template feature

---

docs/getting-started.md
examples/js/app.js
examples/js/data/calendars.js
examples/js/data/schedules.js
index.d.ts
src/js/common/common.js
src/js/controller/base.js
src/js/factory/calendar.js
src/js/handler/daygrid/move.js
src/js/handler/daygrid/resize.js
src/js/handler/month/move.js
src/js/handler/month/resize.js
src/js/handler/time/move.js
src/js/handler/time/resize.js
src/js/view/popup/scheduleCreationPopup.js
src/js/view/template/helper.js
test/app/handler/month/resize.spec.js
test/app/handler/time/move.spec.js
test/app/handler/time/resize.spec.js

* fix #434 : When creating a schedule, passing the category property to 'allday' does not create an all-day schedule.
* fix #421 : When changing the calendar ID in the default edit popup, the calendar is not reflected.
* fix #437 : If a calendar color exists, overwriting the calendar color even if you pass the custom color of the schedule as a property.
* fix #452 : fix: resolve handlebar template fuction override
* It's an issue with the [react wrapper](https://github.com/nhn/toast-ui.react-calendar/issues/18).
---

resolve: issues (fix #434, fix #421, fix #437)

---

src/js/model/schedule.js

This was a feature for Dooray! it's not necessary on master branch
This is a feature for Dooray. Milestone and Task events can have multiple days.
---

fix: remove fixing start of milestone and task  as one day(close #467)

---

src/js/common/datetime.js
test/app/model/event.spec.js
test/fixtures/mock_tasks.json

Fix that the Date instance convert number type.
This patch will also be merged to `feat/dooray` branch.
---

fix: Date convert wrong type as number (close #462)

---

src/js/factory/calendar.js
src/js/view/template/week/time.hbs
src/js/view/week/time.js
src/js/view/week/timeGrid.js

* fix: Fixed resize button being displayed in weekly view(timeGrid) when `isReadOnly=true` as Calendar option(fix #470) 
* fix : Fixed the problem which is not applied when changing template, timezones, calendars property value in `setOptions`(fix #487)
* fix : Resolved an issue where the time range was not normally represented in the time grid when the difference between the main time zone offset and the secondary time zone offset was less than 1 hour (fix #488 ) 
---

Fix: bug fixes (fix #470, fix #487, fix #488)

---

docs/ISSUE_TEMPLATE.md
package.json
src/js/factory/calendar.js
src/js/handler/month/guide.js

* docs: Removed the issue template that can be written in Korean
* fix: Resolves an issue that overwrites default options while month and week options extends
* fix : Fixed an issue where the coordinates in the schedule creation popup were calculated incorrectly if `workweek = true`(fix #480 )
* chore: Change command dev to server on tui-doc
---

fix: fix coordinates in the schedule creation popup(fix #480), docs: fix custom events link, chore: update issue templates

---

src/js/controller/base.js

On schedule update the `raw` content is not considered initially, updated the code accordingly to consider the `raw` content also.
---

fix: Added raw functionality in update schedule (fix #518)

---

src/js/handler/month/guide.js
test/app/handler/month/guide.spec.js

* resolve: Resolve incorrect coordinates to calculate where new calendar creation popups appear when in weekly working time view mode
---

chore: fix broken test case

---

docs/COMMIT_MESSAGE_CONVENTION.md
examples/example00-basic.html
examples/example01-monthly.html
examples/example02-weekly.html
examples/example03-daily.html
examples/example04-2-weeks.html
examples/example05-3-weeks.html
examples/example06-narrow-weekends.html
examples/example07-hide-weekends.html
examples/example08-task-n-schedule.html
examples/example09-task-only.html
examples/example10-common-theme.html
examples/example11-monthly-theme.html
examples/example12-weekly-theme.html
examples/example13-timezone.html
examples/example14-template-for-month.html
examples/example15-template-for-timegrid.html
examples/example16-template-for-popup.html

* chore: change code snippet version for using cdn
* fix: typo (change 'Logger' to 'Longer')
---

chore: change code snippet version for using cdn and fix: typo (Logger to Longer)

---

examples/js/app.js

* fix: when move to prev calendar in monthly view resolve incorrect displayed range text date label on examples(fix #553)
---

Fix incorrect date label on monthly view on example file(fix #553)

---

.github/workflows/detectRuntimeError.yml
createConfigVariable.js
examples/example00-basic.html
examples/example01-monthly.html
examples/example02-weekly.html
examples/example03-daily.html
examples/example04-2-weeks.html
examples/example05-3-weeks.html
examples/example06-narrow-weekends.html
examples/example07-hide-weekends.html
examples/example08-task-n-schedule.html
examples/example09-task-only.html
examples/example10-common-theme.html
examples/example11-monthly-theme.html
examples/example12-weekly-theme.html
examples/example13-timezone.html
examples/example14-template-for-month.html
examples/example15-template-for-timegrid.html
examples/example16-template-for-popup.html
src/js/view/template/week/time.hbs
tuidoc.config.json

* 1f15cfc : chore: remove tui-dom 3.0 dependency (fix #561)
* 522b5a2 : chore: apply github actions for checking error page automatically
---

Remove tui-dom 3.0 dependency on example html files (fix #561) and Apply Github action for checking error example page

---

src/js/view/template/popup/scheduleCreationPopup.hbs

remove superfluous html tags

---

src/js/common/common.js

* fix: check defined properties on beforeUpdateSchedule(fix #463)
---

fix: check defined properties on beforeUpdateSchedule(fix #463)

---

src/js/common/domevent.js
src/js/common/domutil.js
src/js/handler/drag.js
src/js/handler/time/core.js
src/js/view/month/more.js
src/js/view/popup/scheduleCreationPopup.js
src/js/view/popup/scheduleDetailPopup.js
src/js/view/week/timeGrid.js
test/app/handler/time/creationGuide.spec.js

* e4824a1 : improvement: enable text selection on popup(fix #549 )
* a5736c5 : improvement: improved default detail popup location(improvement #568)
* 26ab210 : refactor: add function to get target from event object
---

Enable text selection on popup(fix #549 ) and improved default detail popup location(improvement #568)

---

src/js/view/popup/scheduleCreationPopup.js
test/app/view/scheduleCreationPopup.spec.js

* improvement : improved default creation popup placement(improvement #576 )
---

improvement : improved default creation popup location(improvement #576)

---

src/js/common/domutil.js
src/js/handler/drag.js
test/app/handler/drag.spec.js

* fix: resolve broken TC
* chore: add test code (`preventDefaultWhenNotPopup`)
---

fix: broken TC

---

src/js/view/popup/scheduleCreationPopup.js
test/app/view/scheduleCreationPopup.spec.js

refactor : logic refactoring with schedule creation popup click event handle
fix: eslint
---

Refactor : schedule creation popup save button click handler

---

src/js/common/datetime.js
src/js/controller/viewMixin/week.js
src/js/view/popup/scheduleCreationPopup.js
test/app/datetime.spec.js
test/app/view/scheduleCreationPopup.spec.js

* fix: resolve schedule block position in monthly, weekly view(fix #539)
---

fix: resolve schedule block position(fix #539)

---

examples/js/app.js
src/js/controller/base.js

- [c] It's right issue type on title
fix: set updated category(fix #589)
---

fix: update category(fix #589)

---

src/js/view/popup/scheduleDetailPopup.js

* fix: improved detail popup position in case of long time schedule(fix #592)
---

fix: improved detail popup position in case of long time schedule(fix #592)

---

src/js/view/popup/scheduleDetailPopup.js

fix: resolve broken arrow top position(fix #593)
---

fix: resolve broken arrow top position(fix #593)

---

src/js/view/popup/scheduleCreationPopup.js

fix: always undefined location value of createtion-schedule-popup(fix #615)

---

src/css/variables.styl

perf: remove unused vendor and mpzero stylus functions

---

src/sass/timegrid/column.scss
src/sass/timegrid/timegrid.scss
src/ts/components/draggable.tsx
src/ts/components/hooks/drag.ts
src/ts/components/timegrid/column.tsx
src/ts/components/timegrid/columns.tsx
src/ts/components/timegrid/creationGuide.tsx
src/ts/components/timegrid/currentTimeLabel.tsx
src/ts/components/timegrid/index.ts
src/ts/components/timegrid/timegrid.tsx
src/ts/controller/times.ts
src/ts/controller/week.ts
src/ts/model/index.ts
src/ts/model/schedule.ts
src/ts/time/datetime.ts
src/ts/util/array.ts
src/ts/util/domutil.ts
src/ts/util/index.ts
src/ts/util/keycode.ts
stories/columns.stories.tsx
test-ts/app/components/hooks/drag.spec.ts
test-ts/app/controller/times.spec.ts
test-ts/app/time/datetime.spec.ts
types/tui-code-snippet.d.ts

The important things you need to focus on:
**Components hierarchy**
TimeGrid > ColumnsWithMouse > Column > CreationGuide
**src/ts/controller/times.ts** has finding grid time logic by time and mouse position.
**drag.ts** is not exact hook. Because there is no state management. I want refactoring it as normal module, so any review will be welcome.
---

Add CreationGuide feature in Column for weekly view.

---

package-lock.json
package.json

perf: package.json: remove unused clean-webpack-plugin, extract-loader and style-loader

---

src/css/icons.styl

perf: remove unused css/icons.styl: ic-public

---

src/js/common/datetime.js
src/js/controller/viewMixin/core.js
src/js/controller/viewMixin/month.js
src/js/factory/monthView.js
test/app/datetime.spec.js

fix: fixed a bug that was displayed as a all-day schedule when the end time is 00:00 in a schedule within one day (fix #641 )
**AS-IS**
**TO-BE**
---

fix: fixed a bug that was displayed as a all-day schedule when the end time is 00:00 in a schedule within one day(#641)

---

src/js/common/datetime.js
src/js/controller/viewMixin/core.js
src/js/controller/viewMixin/month.js
src/js/factory/monthView.js
test/app/datetime.spec.js

* fix: fixed a bug that was displayed as a all-day schedule when the end time is 00:00 in a schedule within one day(#641 )
---

Fix: dooray-hotfix 7

---

src/js/handler/month/moveGuide.hbs

fix:monthview content missing while draging all-day schedule(fix #673)

---

src/js/common/common.js

Revert "common.(first/last)In2dArray are not used"

---

.eslintrc
package-lock.json
package.json
src/js/common/timezone.js

style: fix prettier config

---

apps/calendar/.eslintrc.js
apps/calendar/src/util/cssHelper.ts

fix : update eslint rules

---

.github/workflows/test.yml

add test github actions on next branch
---

feat: add test github actions on next branch

---

.github/workflows/test.yml
apps/calendar/test/app/controller/week.spec.ts
apps/calendar/tsconfig.json

fix test action to build date
---

fix: test action to build date

---

.github/workflows/test.yml

fix a branch to checkout in actions
---

fix: branch to checkout in actions

---

.github/workflows/test.yml

**Problems**
* The GitHub test runner runs in GMT, not the local time zone.
**Solutions**
* Add a GitHub action to your configuration that explicitly sets the time zone.
---

chore : action set timezone

---

apps/calendar/src/components/panelgrid/milestone.tsx
apps/calendar/src/components/panelgrid/panelTitle.tsx
apps/calendar/stories/panel.stories.tsx

* add panel title component
---

feat: panel title component

---

apps/calendar/src/components/daygrid/dayGrid.tsx
apps/calendar/src/components/daygrid/gridEvents.tsx
apps/calendar/src/components/events/gridEvent.tsx
apps/calendar/src/components/popup/seeMorePopup.tsx
apps/calendar/src/controller/column.ts
apps/calendar/src/controller/core.ts
apps/calendar/src/controller/month.ts
apps/calendar/src/controller/week.ts
apps/calendar/src/model/schedule.ts
apps/calendar/src/model/scheduleViewModel.ts
apps/calendar/src/util/events.ts
apps/calendar/test/app/controller/core.spec.ts
apps/calendar/test/app/util/events.spec.ts

test : collision events

---

README.md

docs #781 - Added toast_ui.blazor_calendar to wrappers list in readme

---

apps/calendar/src/components/daygrid/grid.tsx
apps/calendar/src/css/daygrid/dayGrid.css

fix: resolve conflict class name (toast-ui-calendar-grid)

---

apps/calendar/package.json
apps/calendar/src/css/icons.css
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/util/dom.ts
apps/calendar/tsconfig.esm.json
apps/calendar/webpack.common.config.js

chore : support ssr

---

apps/calendar/src/components/daygrid/dayName.tsx
apps/calendar/src/components/daygrid/dayNames.tsx
apps/calendar/src/components/daygrid/exceedCountButton.tsx
apps/calendar/src/components/popup/seeMorePopup.tsx
apps/calendar/src/components/view/month.tsx
apps/calendar/src/css/events/grid.css
apps/calendar/src/model/index.ts
apps/calendar/src/template/default.tsx
apps/calendar/src/template/index.ts
apps/calendar/stories/dayNames.stories.tsx
apps/calendar/stories/monthView.stories.tsx
apps/calendar/test/app/template/template.spec.tsx
apps/calendar/types/components/daygrid/dayNames.d.ts

refactor : remove unnecessary code

---

apps/calendar/src/components/view/month.tsx

fix: resolve getMousePosition function for creation guide

---

apps/calendar/src/components/daygrid/cell.tsx
apps/calendar/src/components/daygrid/dayGrid.tsx
apps/calendar/src/components/daygrid/grid.tsx
apps/calendar/src/components/daygrid/gridEvents.tsx
apps/calendar/src/components/panelgrid/dayGridEvents.tsx
apps/calendar/src/components/popup/seeMorePopup.tsx
apps/calendar/src/css/events/grid.css
apps/calendar/src/theme/preset.ts
apps/calendar/src/theme/themeProps.ts
apps/calendar/src/util/units.ts
apps/calendar/test/app/util/units.spec.ts
apps/calendar/types/theme.d.ts

* apply theme for month view
---

feat : month view theme

---

apps/calendar/src/components/daygrid/cell.tsx
apps/calendar/src/components/daygrid/dayGrid.tsx
apps/calendar/src/components/daygrid/grid.tsx
apps/calendar/src/components/hooks/theme.ts
apps/calendar/src/components/panelgrid/dayGridEvents.tsx
apps/calendar/src/components/popup/seeMorePopup.tsx
apps/calendar/src/components/popup/seeMoreTitle.tsx
apps/calendar/src/components/provider/store.tsx
apps/calendar/src/components/provider/theme.tsx
apps/calendar/src/components/ui/text.tsx
apps/calendar/src/components/view/Main.tsx
apps/calendar/src/components/view/day.tsx
apps/calendar/src/components/view/month.tsx
apps/calendar/src/components/view/week.tsx
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/model/context.ts
apps/calendar/src/model/index.ts
apps/calendar/src/modules/index.ts
apps/calendar/src/modules/theme.ts
apps/calendar/stories/panel.stories.tsx
apps/calendar/stories/util/providerWrapper.tsx
apps/calendar/test/helper/storeProvider.tsx
apps/calendar/types/store.d.ts

* extract the application theme from the store
* It can be used by calling the `useTheme` hook
---

refactor: introduce useTheme hook

---

apps/calendar/src/components/daygrid/gridWithMouse.tsx
apps/calendar/src/components/events/gridEvent.tsx
apps/calendar/src/components/events/resizeIcon.tsx
apps/calendar/src/components/hooks/drag.ts
apps/calendar/src/components/timegrid/columns.tsx
apps/calendar/test/app/components/hooks/drag.spec.ts
apps/calendar/test/helper/index.ts
apps/calendar/types/util.d.ts

- The previous `useDrag` hook has some potential problems such as infinite event binding and reassigning every function on re-render.
- So this PR refines the `useDrag` hook following an ideal hook implementation.
- Memoize functions
- Let the effect handle event binding
- Make event binding/removing happens at the right timing and to the right function
- Reference: https://usehooks.com/useEventListener/
---

refactor: refine `useDrag` hook

---

apps/calendar/src/components/hooks/panelContainer.ts
apps/calendar/src/components/timegrid/collapseButton.tsx
apps/calendar/src/components/timegrid/columns.tsx
apps/calendar/src/components/timegrid/creationGuide.tsx
apps/calendar/src/components/timegrid/index.ts
apps/calendar/src/components/timegrid/times.tsx
apps/calendar/src/components/view/month.tsx
apps/calendar/src/util/cssHelper.ts
apps/calendar/src/util/utils.ts
apps/calendar/test/app/controller/times.spec.ts
apps/calendar/test/app/util/cssHelper.spec.ts

- Currently `cls` function and `classnames` function are used together, which is redundant.
- So I changed `cls`'s interface like `classnames` and usages their comsumers.
---

refactor: refine `cls` helper function

---

apps/calendar/src/store/hook.ts
apps/calendar/src/store/internal.ts
apps/calendar/test/app/store/hook.spec.ts
apps/calendar/types/store.d.ts

* Inspire by [Zustand](https://github.com/pmndrs/zustand) library
* can create a store using `createStoreHook`.
* recommend creating a slice of states and separated dispatchers.
* can handle derived states with custom hooks.
---

feat: implement new state management module

---

apps/calendar/jest.config.js
apps/calendar/package-lock.json
apps/calendar/package.json
apps/calendar/src/store/context.ts
apps/calendar/src/store/hook.ts
apps/calendar/test/app/store/context.spec.tsx
apps/calendar/test/jestSetup.ts
apps/calendar/types/store.d.ts

- Implement `createStoreContext` to inject store hooks with Provider.
- Because of the rules of hooks, injecting `useStore` hook as the context value wouldn't work.
- This will replace the current `StoreProvider`.
---

feat: implement new `StoreProvider`

---

index.d.ts
test/types/type-tests.ts

- Fix the wrong type definition of the `beforeCreateSchedule` event.
- Resolves #870 
---

fix: improve type definition of `beforeCreationSchedule` event (#870)

---

package-lock.json
package.json
src/js/view/month/month.js
src/js/view/month/weekdayInMonth.js
src/js/view/week/dayGrid.js
src/js/view/week/dayGridSchedule.js
src/js/view/week/dayname.js
src/js/view/week/timeGrid.js

- Update dependencies (including `package-lock.json` file update)
- `tui-date-picker`
- `tui-time-picker` - should be updated later this week
- add `dompurify` as a dependency + sanitize some templates before injecting HTML
- ViewModel can have unsanitized string so it might be vulnerable.
---

fix: xss vulnerability (#752)

---

.github/actions/get-target-version/action.yml
.github/actions/install-dependencies/action.yml
.github/workflows/publish.yml
package-lock.json
package.json
scripts/publishToCDN.js

- This PR is a setup for the automated package deployment.
- Requires a commit having a message as the new version.
- Created a small script following [Editor's one](https://github.com/nhn/tui.editor/blob/master/scripts/publish-cdn.js)
---

env: enable automated package deployment

---

README.md
src/js/controller/base.js
src/js/factory/calendar.js
src/js/view/month/month.js
src/js/view/month/weekdayInMonth.js
src/js/view/week/dayGrid.js
src/js/view/week/dayGridSchedule.js
src/js/view/week/dayname.js
src/js/view/week/timeGrid.js

- This PR fixes the wrong implementation of the XSS prevention in #879.
---

fix: refine wrong DOM sanitization

---

apps/calendar/src/theme/preset.ts
apps/calendar/src/theme/themeProps.ts
apps/calendar/stories/util/mockCalendars.ts

* remove storybook event
* AS-IS
* ![스크린샷 2021-11-08 오후 3 15 30](https://user-images.githubusercontent.com/28647773/140693054-110f225c-c7af-44ef-96ca-9bdc14d3d512.png)
* TO-BE
* ![스크린샷 2021-11-08 오후 3 14 48](https://user-images.githubusercontent.com/28647773/140692994-4b7cd323-9577-47f2-9ef6-4091f2d1cdbe.png)
* organize theme props
---

refactor: storybook theme

---

apps/calendar/src/components/dayGridWeek/gridRow.tsx
apps/calendar/src/components/layout.tsx
apps/calendar/src/components/panel.tsx
apps/calendar/src/components/view/day.tsx
apps/calendar/src/components/view/week.tsx
apps/calendar/src/constants/layout.ts
apps/calendar/src/constants/style.ts
apps/calendar/src/css/daygrid/dayNames.css
apps/calendar/src/css/panel/allday.css

* add scrollbar area
* fix dayname height to fit container
---

feat: add scrollbar area

---

apps/calendar/.eslintrc.js
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/time/date.ts
apps/calendar/src/time/timezone.ts
apps/calendar/stories/columns.stories.tsx
apps/calendar/stories/dayGridMonth.stories.tsx
apps/calendar/stories/dayView.stories.tsx
apps/calendar/stories/eventFormPopup.stories.tsx
apps/calendar/stories/gridHeader.stories.tsx
apps/calendar/stories/gridRow.stories.tsx
apps/calendar/stories/main.stories.tsx
apps/calendar/stories/monthView.stories.tsx
apps/calendar/stories/timegrid.stories.tsx
apps/calendar/stories/util/randomEvents.ts
apps/calendar/stories/weekView.stories.tsx
apps/calendar/test/app/calendar.spec.ts
apps/calendar/test/app/components/hooks/drag.spec.tsx
apps/calendar/test/app/components/popup/eventFormPopup.spec.tsx
apps/calendar/test/app/controller/times.spec.ts
apps/calendar/test/app/store/index.spec.tsx
apps/calendar/test/app/time/timezone.spec.ts
apps/calendar/test/app/util/gridHelper.spec.ts
apps/calendar/types/option.d.ts

- improve eslint import rule
- The external library is above alias.
---

env: improve eslint import rule

---

apps/calendar/src/components/floatingLayer.tsx
apps/calendar/src/components/popup/eventDetailPopup.tsx
apps/calendar/src/components/popup/eventDetailSectionButton.tsx
apps/calendar/src/components/popup/eventDetailSectionDetail.tsx
apps/calendar/src/components/popup/eventDetailSectionHeader.tsx
apps/calendar/src/components/popup/eventFormPopup.tsx
apps/calendar/src/css/icons.css
apps/calendar/src/css/popup/common.css
apps/calendar/src/css/popup/detail.css
apps/calendar/src/css/popup/form.css
apps/calendar/src/css/popup/index.css
apps/calendar/stories/eventDetailPopup.stories.tsx
apps/calendar/stories/eventFormPopup.stories.tsx
apps/calendar/test/app/components/popup/eventDetailPopup.spec.tsx
apps/calendar/types/store.d.ts

- add `eventDetailPopup`
- only add UI
- screen shot
---

feat: event detail popup view

---

apps/calendar/playwright/week.spec.ts
apps/calendar/src/components/dayGridMonth/gridCell.tsx
apps/calendar/src/components/dayGridWeek/alldayGridRow.tsx
apps/calendar/src/components/floatingLayer.tsx
apps/calendar/src/components/popup/eventFormPopup.tsx
apps/calendar/src/components/view/day.tsx
apps/calendar/src/components/view/week.tsx
apps/calendar/src/constants/popup.ts
apps/calendar/src/css/popup/form.css
apps/calendar/stories/weekView.stories.tsx
apps/calendar/test/app/components/popup/eventDetailPopup.spec.tsx
apps/calendar/test/app/components/popup/eventFormPopup.spec.tsx
apps/calendar/types/store.d.ts

- display event form popup when grid selection created
- add `playwright` test
https://user-images.githubusercontent.com/28647773/145341124-393ec228-0eaa-4202-99de-9ea32a07e6f0.mov
---

feat: display event form popup

---

README.md

working Angular 12 wrapper ngx-mat-tui-calendar has been released
---

docs: added Angular wrapper ngx-mat-tui-calendar to README##wrappers

---

apps/calendar/src/components/dayGridMonth/gridCell.tsx
apps/calendar/src/components/layout.tsx
apps/calendar/src/contexts/layoutContainerRef.tsx

* Passing `RefObject` is unstable.
* so this PR makes sure the layout container is mounted and passes it to children.
---

refactor: pass layout container dom node itself

---

apps/calendar/src/components/events/horizontalEvent.tsx
apps/calendar/src/hooks/dayGridWeek/alldayGridRowEventMove.ts

- not move and resize read-only event
- fix not work moving event properly
---

feat: controll readonly event

---

apps/calendar/src/hooks/dayGridCommon/dayGridSelection.ts
apps/calendar/src/hooks/dayGridMonth/dayGridMonthEventMove.ts
apps/calendar/types/components/daygrid/gridSelection.d.ts

- Using refs makes codes hard to follow.
- Rethinking custom hook implementations not to use refs.
---

refactor: remove unnecessary `useRef` usages

---

apps/calendar/src/hooks/common/__tests__/customEvent.spec.tsx
apps/calendar/src/hooks/common/customEvent.ts

- This PR makes the event bus easier to manage the lifecycle of custom event registration.
---

refactor: implement `useCustomEvent` hook

---

apps/calendar/src/hooks/dayGridWeek/alldayGridRowEventResize.ts

- update event only when resizing ends on a different date
---

fix: update event only when resizing ends on a different date

---

apps/calendar/playwright/assertions.ts
apps/calendar/playwright/month/eventResizing.spec.ts
apps/calendar/src/components/dayGridMonth/dayGridMonth.tsx
apps/calendar/src/components/dayGridMonth/monthEvents.tsx
apps/calendar/src/components/dayGridMonth/resizingEventShadow.tsx
apps/calendar/src/components/events/horizontalEvent.tsx
apps/calendar/src/components/events/resizeIcon.tsx
apps/calendar/src/components/view/month.tsx
apps/calendar/src/constants/keyboard.ts
apps/calendar/src/hooks/common/drag.ts
apps/calendar/src/hooks/common/keydownEvent.ts
apps/calendar/src/hooks/dayGridCommon/popupWithDayGridSelection.ts
apps/calendar/src/hooks/dayGridMonth/dayGridMonthEventMove.ts
apps/calendar/src/hooks/dayGridMonth/dayGridMonthEventResize.ts
apps/calendar/src/hooks/dayGridWeek/alldayGridRowEventMove.ts
apps/calendar/src/hooks/dayGridWeek/alldayGridRowEventResize.ts
apps/calendar/src/hooks/event/currentPointerPositionInGrid.ts
apps/calendar/src/model/eventUIModel.ts
apps/calendar/src/slices/dnd.ts
apps/calendar/src/utils/array.ts
apps/calendar/src/utils/keyboard.ts
apps/calendar/stories/dayGridMonth.stories.tsx
apps/calendar/types/grid.d.ts
package-lock.json
package.json

- Implemented `useDayGridMonthEventResize` hook.
- Extracted bunch of utilities such as `useKeydownEvent`, `useCurrentPointerPositionInGrid`, etc.
- Improved key press detecting usages.
---

feat: implement event resizing in month view

---

apps/calendar/src/components/dayGridCommon/dayName.tsx
apps/calendar/src/components/dayGridCommon/gridHeader.tsx
apps/calendar/src/helpers/dayName.ts
apps/calendar/src/template/default.tsx
apps/calendar/types/eventBus.d.ts
apps/calendar/types/template.d.ts

- add custom event `clickDayname`
https://user-images.githubusercontent.com/28647773/150058507-313dbc61-5fd0-4fc4-ba6b-bd0ae41cb563.mov
---

fix: add custom event `clickDayname`

---

apps/calendar/src/components/template.tsx
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/utils/sanitizer.ts
apps/calendar/stories/weekView.stories.tsx
apps/calendar/test/app/template/template.spec.tsx
apps/calendar/test/jestSetup.ts
package-lock.json
package.json

feat: Add dompurify on Template

---

apps/calendar/src/contexts/__tests__/eventBus.spec.tsx
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/utils/eventBus.ts

* should be able to turn off specific handler among handlers
---

fix: missing `EventBus#off` implementation

---

apps/calendar/src/components/events/horizontalEvent.tsx
apps/calendar/src/components/popup/eventFormPopup.tsx
apps/calendar/types/eventBus.d.ts

- add custom event `clickEvent`
https://user-images.githubusercontent.com/28647773/150101591-8036c116-58a6-458e-b702-f53453960b59.mov
---

feat: custom event `clickEvent`

---

apps/calendar/src/calendarContainer.tsx
apps/calendar/src/components/dayGridMonth/gridCell.tsx
apps/calendar/src/components/events/horizontalEvent.tsx
apps/calendar/src/components/popup/closePopupButton.tsx
apps/calendar/src/components/popup/eventDetailPopup.tsx
apps/calendar/src/components/popup/eventFormPopup.tsx
apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
apps/calendar/src/constants/popup.ts
apps/calendar/src/contexts/floatingLayer.tsx
apps/calendar/src/css/popup/common.css
apps/calendar/src/css/popup/seeMore.css
apps/calendar/src/hooks/dayGridCommon/popupWithDayGridSelection.ts
apps/calendar/src/selectors/popup.ts
apps/calendar/src/slices/popup.ts
apps/calendar/stories/eventDetailPopup.stories.tsx
apps/calendar/stories/eventFormPopup.stories.tsx
apps/calendar/test/app/components/popup/eventDetailPopup.spec.tsx
apps/calendar/test/app/components/popup/eventFormPopup.spec.tsx
apps/calendar/types/eventBus.d.ts

- add custom event `clickMoreEventsBtn`
- add 3 popup slots in floating layer
- split popup slice and dispatchers each type
https://user-images.githubusercontent.com/28647773/150448607-5660376c-280f-4315-8297-1d5666531ec6.mov
---

feat: custom event `clickMoreEventsBtn`

---

apps/calendar/src/controller/base.ts
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/slices/calendar.ts

- add `CalendarState` type to calendar dispatcher
- remove JSDoc related createEvents method
---

refactor: add `CalendarState` type and remove JSDoc

---

apps/calendar/src/factory/calendarControl.tsx

- implement `updateEvent` method
---

feat: implement `updateEvent` instance method

---

apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/slices/calendar.ts

- implement `deleteEvent` instance method
---

feat: implement `deleteEvent` instance method

---

apps/calendar/src/components/popup/eventDetailPopup.tsx
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/slices/calendar.ts
apps/calendar/types/eventBus.d.ts

- implement `beforeDeleteEvent` custom event
https://user-images.githubusercontent.com/28647773/152484330-d358f516-11dc-410f-b754-a7ab363975a2.mov
---

feat: implement `beforeDeleteEvent` custom event

---

package-lock.json
package.json
src/css/weekday.styl
src/js/common/floatingLayer.js
src/js/factory/monthView.js
src/js/factory/weekView.js
src/js/theme/theme.js
src/js/view/layout.js
src/js/view/template/week/dayGridSchedule.hbs
src/js/view/week/dayGridSchedule.js

- Fixed a problem when user disables `useCreationPopup` or `useDetailPopup` options with `setOptions` method, and enables it.
- Fix #699
- Fixed various minor issues
- Fix #1006, #1007, #1008, #1015, #1023
---

fix: prevent missing view error on toggling popup options (fix #699)

---

apps/calendar/src/factory/calendarControl.spec.ts
apps/calendar/src/factory/calendarControl.tsx

- implement `changeView` and `getViewName` method
---

feat: change view method

---

apps/calendar/.eslintrc.js
apps/calendar/index.d.ts
apps/calendar/src/factory/calendarControl.spec.tsx
apps/calendar/src/factory/calendarControl.tsx

- implement `destroy`, `openFormPopup` method
- turn off rule for todo comment
---

feat: implement destroy and openFormPopup method

---

apps/calendar/src/components/dayGridMonth/cellHeader.tsx
apps/calendar/src/components/view/day.tsx
apps/calendar/src/components/view/month.tsx
apps/calendar/src/components/view/week.tsx
apps/calendar/src/factory/calendarControl.spec.tsx
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/slices/view.spec.ts
apps/calendar/src/slices/view.ts

- implement `move`, `prev`, `next`, `today`, `setDate`, `getDate`
- add tests for `prev`, `next`, `today`, `setDate`, `getDate`
---

feat: implement methods related renderDate

---

apps/calendar/src/factory/calendarControl.spec.tsx
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/slices/calendar.ts
apps/calendar/src/theme/index.ts

- implement instance method
- `setTheme`
- `getOptions`
- `setOptions`
- `setCalendars`
- `setCalendarColor`
---

feat: method related theme, options, calendars

---

apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
apps/calendar/src/components/timeGrid/currentTimeLabel.tsx
apps/calendar/src/components/timeGrid/timeColumn.tsx
apps/calendar/src/components/timeGrid/timeGrid.spec.tsx
apps/calendar/src/components/timeGrid/timeGrid.tsx
apps/calendar/src/components/timeGrid/times.tsx
apps/calendar/src/css/timegrid/timegrid.css
apps/calendar/src/css/timegrid/times.css
apps/calendar/src/hooks/common/useInterval.spec.ts
apps/calendar/src/hooks/common/useInterval.ts
apps/calendar/src/hooks/common/useIsMounted.spec.ts
apps/calendar/src/hooks/common/useIsMounted.ts
apps/calendar/src/test/utils.tsx

- Refined the `CurrentTimeIndicator` component
- use theme color
- removed unused props (NOTE: `dateDifference` might be needed when applying timezone)
- Implemented useful custom hooks: useInterval, useIsMounted
---

refactor: current time indicator

---

apps/calendar/src/constants/error.ts
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/time/datetime.spec.ts
apps/calendar/src/time/datetime.ts
apps/calendar/stories/times.stories.tsx

- implement `addMonth` and `subtractMonth`
- If the rendenderDate is at the end of the month, fix that `prev` and `next` do not work properly.
---

fix: prev and next work properly

---

.github/composite-actions/install-dependencies/action.yml
.github/workflows/test.yml

* change ci runner to `ubuntu-latest`
* use `lerna bootstrap` command for bootstraping & pre-building dependency
---

env: change ci runner to ubuntu-latest

---

apps/calendar/src/components/timeGrid/column.tsx

* change the order of components so that the guide component is drawn above event components
* in the day and week view
* The order: Grid selection > Resizing Guide > Event > Background event
---

fix: change the order of components so that the guide component is drawn above event components

---

apps/calendar/src/components/dayGridMonth/movingEventShadow.tsx
apps/calendar/src/components/events/horizontalEvent.tsx
apps/calendar/src/components/events/timeEvent.tsx
apps/calendar/src/components/timeGrid/resizingGuideByColumn.tsx
apps/calendar/src/hooks/common/useWhen.ts
apps/calendar/src/hooks/dayGridMonth/useDayGridMonthEventMove.ts
apps/calendar/src/hooks/dayGridMonth/useDayGridMonthEventResize.ts
apps/calendar/src/hooks/dayGridWeek/useAlldayGridRowEventMove.ts
apps/calendar/src/hooks/dayGridWeek/useAlldayGridRowEventResize.ts
apps/calendar/src/hooks/event/useDraggingEvent.ts
apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.spec.tsx
apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.ts
apps/calendar/src/hooks/timeGrid/useTimeGridEventResize.ts
apps/calendar/src/selectors/dnd.ts

- Found and Fixed clearing state logics when dragging ends
- Expanded the role of `useDraggingEvent` hook so that we don't have to care the lifecycle of dragging
- chore: move timegrid event resizing logic to custom hook
---

fix: mixed(and wrong) drag and drop behaviors

---

apps/calendar/src/controller/base.spec.ts
apps/calendar/src/controller/base.ts
apps/calendar/src/controller/core.spec.ts
apps/calendar/src/controller/core.ts
apps/calendar/src/controller/month.ts
apps/calendar/src/controller/week.spec.ts
apps/calendar/src/controller/week.ts
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/setupTests.ts
apps/calendar/src/utils/collection.spec.ts
apps/calendar/src/utils/collection.ts
apps/calendar/tsconfig.test.json

* use ES6 `Map` in the `Collection`
---

refactor: use ES6 `Map` in the `Collection`

---

apps/calendar/playwright/day/timeGridEventMoving.e2e.ts
apps/calendar/playwright/day/timeGridEventResizing.e2e.ts
apps/calendar/playwright/day/timeGridSelection.e2e.ts
apps/calendar/playwright/month/eventMoving.e2e.ts
apps/calendar/playwright/month/eventResizing.e2e.ts
apps/calendar/playwright/utils.ts
apps/calendar/playwright/week/alldayGridEventDragAndDrop.e2e.ts
apps/calendar/playwright/week/timeGridEventMoving.e2e.ts
apps/calendar/playwright/week/timeGridEventResizing.e2e.ts
apps/calendar/playwright/week/timeGridSelection.e2e.ts
apps/calendar/src/hooks/dayGridWeek/useAlldayGridRowEventMove.ts
playwright.config.ts

- fix moving horizontal event properly
- reimplement `dragAndDrop` test utils using mouse down, move, up
- AS-IS
- TO-BE
https://user-images.githubusercontent.com/28647773/163769864-778a038e-8d6a-4b3a-ac41-3adc00823ff0.mov
---

fix: move horizontal event properly

---

apps/calendar/playwright/week/timeGridEventClick.e2e.ts
apps/calendar/src/components/events/timeEvent.tsx

- display detail popup when timeGrid event is clicked
https://user-images.githubusercontent.com/28647773/163900464-250fde4a-9c8d-4238-979b-5ba44ef87d48.mov
---

feat: display detail popup in timegrid event

---

apps/calendar/src/css/events/time.css

- decide resize handler's height
https://user-images.githubusercontent.com/28647773/163957777-453eee5f-cab7-44c3-97b3-a63dcf158760.mov
---

chore: decide resize handler's height

---

.github/composite-actions/install-dependencies/action.yml
apps/calendar/playwright/day/timeGridEventMoving.e2e.ts
apps/calendar/playwright/day/timeGridEventResizing.e2e.ts
apps/calendar/playwright/day/timeGridScrollSync.e2e.ts
apps/calendar/playwright/month/eventMoving.e2e.ts
apps/calendar/playwright/month/eventResizing.e2e.ts
apps/calendar/playwright/utils.ts
apps/calendar/playwright/week/alldayGridEventDragAndDrop.e2e.ts
apps/calendar/playwright/week/timeGridEventResizing.e2e.ts
apps/calendar/playwright/week/timeGridScrollSync.e2e.ts
package-lock.json
package.json
playwright.config.ts

- Added new dev dependency: [`wait-for-expect`](https://github.com/TheBrainFamily/wait-for-expect)
- it will be useful when waiting for certain interactions like drag and drop.
- But it seems the timing control is not working well in CI. so keep the `slowMo` option in CI.
---

test: fix e2e test suite

---

apps/calendar/index.d.ts
apps/calendar/playwright/day/timeGridSelection.e2e.ts
apps/calendar/playwright/month/gridSelection.e2e.ts
apps/calendar/playwright/week/dayGridSelection.e2e.ts
apps/calendar/playwright/week/timeGridSelection.e2e.ts
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/hooks/common/useClickPrevention.spec.tsx
apps/calendar/src/hooks/common/useClickPrevention.ts
apps/calendar/src/hooks/gridSelection/useGridSelection.spec.tsx
apps/calendar/src/hooks/gridSelection/useGridSelection.ts
apps/calendar/src/slices/options.ts
apps/calendar/src/utils/requestTimeout.spec.ts
apps/calendar/src/utils/requestTimeout.ts
apps/calendar/types/options.d.ts
apps/calendar/types/store.d.ts

* [BREAKING CHANGE] disableDblClick and disableClick options are deprecated.
* Instead, use `gridSelection.enableDblClick` and `gridSelection.enableClick`.
```js
const options = {
// disableDblClick: true, // deprecated
// disableClick: true, // deprecated
gridSelection: {
enableDblClick: false,
enableClick: false
}
};
// Or, set by a boolean value.
const options = {
gridSelection: false // Both enableDblClick and enableClick are false.
};
```
* The default values of `gridSelection.enableDblClick` and `gridSelection.enableClick` are `true`.
* Implement `gridSelection.enableDblClick` and `gridSelection.enableClick`.
* Fix to show a creationPopup only once when double clicking.
---

feat: implement gridSelection.enableDblClick and gridSelection.enableClick options

---

apps/calendar/playwright/day/timeGridEventMoving.e2e.ts
apps/calendar/playwright/week/timeGridEventMoving.e2e.ts
apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.ts

- calibrate timed event's height
- add tests for calibrating timed event's height when dragging
- AS-IS
- TO-BE
https://user-images.githubusercontent.com/28647773/166189500-67c27fc3-c649-42a4-93ed-f28448b2a3f6.mov
https://user-images.githubusercontent.com/28647773/166189558-be7bc748-1656-4ab6-a62c-66b8e78f1be4.mov
---

feat: calibrate timed event height

---

apps/calendar/src/constants/statistics.ts
apps/calendar/src/factory/calendarControl.spec.tsx
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/types/tui-code-snippet.d.ts

* Implement the `usageStatistics` option.
---

feat: implement usageStatistics option

---

playwright.config.ts

* replace lerna to npm workspace in playwright.config.ts
---

env: replace lerna to npm workspace in playwright.config.ts

---

apps/calendar/src/components/dayGridCommon/dayName.tsx
apps/calendar/src/components/dayGridCommon/gridHeader.tsx
apps/calendar/src/components/dayGridWeek/gridCell.tsx
apps/calendar/src/components/template.tsx
apps/calendar/src/css/panel/allday.css
apps/calendar/src/template/default.tsx

- apply week grid template
---

feat: apply grid template for week

---

apps/calendar/src/components/dayGridMonth/cellHeader.tsx
apps/calendar/src/components/dayGridMonth/gridCell.tsx
apps/calendar/src/components/dayGridMonth/moreEventsButton.tsx
apps/calendar/src/components/view/month.tsx
apps/calendar/src/constants/grid.ts
apps/calendar/src/helpers/dayName.ts
apps/calendar/src/template/default.tsx
apps/calendar/src/utils/keyboard.ts
apps/calendar/src/utils/string.spec.ts
apps/calendar/src/utils/string.ts

- apply month grid template
---

feat: apply grid header & footer template for month view

---

apps/calendar/src/components/popup/closePopupButton.tsx
apps/calendar/src/components/popup/eventFormPopup.tsx
apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
apps/calendar/src/components/template.tsx
apps/calendar/src/css/popup/common.css
apps/calendar/src/css/popup/seeMore.css
apps/calendar/src/template/default.tsx

- apply month more events popup template
- header
- close button
---

feat: apply month popup template

---

apps/calendar/src/components/dayGridWeek/gridCell.tsx
apps/calendar/stories/docs/ko/apis/template.stories.mdx

docs: template docs

---

apps/calendar/src/components/dayGridMonth/cellHeader.tsx
apps/calendar/src/components/timeGrid/timeColumn.tsx
apps/calendar/src/components/timeGrid/timeGrid.tsx
apps/calendar/src/components/timeGrid/times.tsx
apps/calendar/src/components/timeGrid/timezoneLabels.tsx
apps/calendar/src/components/view/day.spec.tsx
apps/calendar/src/hooks/timezone/useEventsWithTimezone.ts
apps/calendar/src/hooks/timezone/usePrimaryTimezone.ts
apps/calendar/src/hooks/timezone/useTZConverter.spec.ts
apps/calendar/src/hooks/timezone/useTZConverter.ts

- This PR applies `customOffsetCalculator` option to components.
- When the `customOffsetCalculator` is given, it should override the default timezone offset calculator.
- Implemented utility hooks
- Using primary timezone and getting current time in the primary timezone
- Converter function to picking right converter by options.
---

feat: apply custom timezone offset calculator through components

---

apps/calendar/docs/ko/apis/TZDate.stories.mdx
apps/calendar/scripts/build-esm.js
apps/calendar/src/factory/calendarControl.tsx
apps/calendar/src/factory/month.spec.tsx
apps/calendar/src/time/date.ts
apps/calendar/src/time/timezone.spec.ts
apps/calendar/src/time/timezone.ts

docs: TZDate

---

apps/calendar/docs/ko/apis/template.stories.mdx
apps/calendar/index.d.ts
apps/calendar/src/components/events/horizontalEvent.spec.tsx
apps/calendar/src/components/events/horizontalEvent.tsx
apps/calendar/src/components/events/timeEvent.spec.tsx
apps/calendar/src/components/events/timeEvent.tsx
apps/calendar/src/components/view/week.spec.tsx
apps/calendar/src/constants/style.ts
apps/calendar/src/controller/week.ts
apps/calendar/src/factory/__snapshots__/calendarControl.spec.tsx.snap
apps/calendar/src/helpers/css.ts
apps/calendar/src/hooks/calendar/useCalendarColor.ts
apps/calendar/src/model/eventModel.spec.ts
apps/calendar/src/model/eventModel.ts
apps/calendar/src/template/default.tsx
apps/calendar/stories/column.stories.tsx
apps/calendar/stories/timegrid.stories.tsx
apps/calendar/types/components/events/gridEvent.d.ts
apps/calendar/types/events.d.ts
apps/calendar/types/template.d.ts

- Commented background event concepts. It will be uncommented when available.
- Applied the `customStyle` property and color values to EventModel.
- Removed polymorphic templates such as `event` and `dayGridTitle`.
- Fixed error when there is no timed event in the week/day view.
---

fix: minor bugs and not implemented features

---

apps/calendar/docs/ko/guide/migration_v2.stories.mdx

- write v2 migration guide
---

docs: write v2 migration guide

---

.github/workflows/publish-calendar.yml
apps/calendar/package.json

* add workflow to publish @toast-ui/calendar
* except wrappers
* for alpha release
---

env: add workflow to publish @toast-ui/calendar

---

apps/calendar/src/components/events/horizontalEvent.spec.tsx
apps/calendar/src/components/events/timeEvent.spec.tsx
apps/calendar/src/controller/core.spec.ts
apps/calendar/src/controller/core.ts
apps/calendar/src/factory/calendarControl.spec.tsx
apps/calendar/src/helpers/grid.spec.ts
apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.spec.tsx
apps/calendar/src/model/eventUIModel.ts
apps/calendar/stories/events.stories.tsx
apps/calendar/stories/helper/event.ts

* remove EventUIModel.create and use new EventUIModel
---

refactor: remove EventUIModel.create and use new EventUIModel

---

.github/workflows/publish-calendar.yml

- Added steps for publishing docs in the github action workflow
---

env: add action steps to publish docs

---

apps/calendar/playwright/day/timeGridEventMoving.e2e.ts
apps/calendar/playwright/week/timeGridEventMoving.e2e.ts
apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.ts

- calibrate timed event's height while dragging
---

feat: calibrate timed event move

---

apps/calendar/src/factory/calendarControl.spec.tsx
apps/calendar/src/factory/calendarControl.tsx

- `setDate` and `today` reflects `renderRange`
---

fix: setDate reflects renderRange

---

README.md
apps/calendar/README.md
apps/calendar/src/components/view/week.spec.tsx
docs/README.md
docs/en/apis/calendar.md
docs/en/apis/event-object.md
docs/en/apis/options.md
docs/en/apis/template.md
docs/en/apis/theme.md
docs/en/apis/tzdate.md
docs/en/guide/getting-started.md
docs/en/guide/migration-guide-v2.md
docs/ko/apis/event-object.md
docs/ko/apis/options.md
docs/ko/apis/template.md
docs/ko/guide/migration-guide-v2.md

- English docs are ready.
- Contents in READMEs are updated.
- Fixed typos
- Changed npm badge links
---

docs: english docs

---

apps/calendar/src/components/events/horizontalEvent.tsx
apps/calendar/src/components/events/timeEvent.tsx

Fixed details popup not opening on click for read only events

fix: details popup not opening on click for read only events

---

docs/en/guide/migration-guide-v2.md
docs/ko/guide/migration-guide-v2.md

- add a guide on changing the filename
---

docs: add a guide on changing the filename

---

apps/calendar/src/components/events/horizontalEvent.spec.tsx
apps/calendar/src/components/events/timeEvent.spec.tsx

This PR adds missing test cases for #1178. 
---

test: add test cases for #1178

---

apps/calendar/examples/00-calendar-app.html
apps/calendar/examples/01-monthly-view-basic.html
apps/calendar/examples/02-monthly-view-2weeks.html
apps/calendar/examples/03-monthly-view-3weeks.html
apps/calendar/examples/04-weekly-view.html
apps/calendar/examples/05-weekly-view-no-event-view.html
apps/calendar/examples/06-daily-view.html
apps/calendar/examples/07-narrow-weekends.html
apps/calendar/examples/08-hidden-weekends.html
apps/calendar/examples/09-timezone.html
apps/calendar/examples/10-theme-common.html
apps/calendar/examples/11-theme-monthly.html
apps/calendar/examples/12-theme-weekly.html
apps/calendar/examples/13-template-monthly.html
apps/calendar/examples/14-template-weekly.html
apps/calendar/examples/15-template-popup.html

- Use a minified IE11 bundle file in the examples.
- Use different CDN for the `chance` library to support IE11.
---

refactor: support IE11 in the examples

---

.github/workflows/publish-calendar.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-wrappers.yml
apps/calendar/README.md
apps/react-calendar/README.md
package.json
scripts/replaceLinkInReadme.js

- Update relative links in README.md before publishing npm and tuidoc.
- To fix the issue that relative links do not work properly in NPM packages of wrappers and tuidoc.
---

env: update relative links in readme before publishing npm and tuidoc

---

CONTRIBUTING.md
apps/calendar/README.md
apps/react-calendar/README.md
apps/vue-calendar/README.md
apps/vue-calendar/package.json

- Update contributing guidelines.
---

docs: update contributing guidelines

---

apps/vue-calendar/README.md

Fixed missing `/dist/` on importing CSS file.
---

docs: fixed import css path

---

docs/en/apis/calendar.md
docs/en/apis/event-object.md

Some translation improvements were missing from #1181.
---

docs: apply missing translation improvements

---

apps/calendar/src/index.ts
apps/react-calendar/src/index.tsx

The react wrapper build is failing because it's importing types from the inaccessible directory for Vite.
So rather than changing the `exports` field in the `package.json` of the calendar, exports more types for future development.
---

feat: export more types

---

apps/calendar/src/components/popup/eventFormPopup.tsx
apps/calendar/src/factory/calendarCore.tsx

- Set the default value of the event form popup's calendar select properly.
- chore: Destroy theme store when calling the `destroy` method.
---

fix: set default calendarId properly

---

apps/calendar/playwright/day/timeGridEventMoving.e2e.ts
apps/calendar/playwright/day/timeGridEventResizing.e2e.ts
apps/calendar/playwright/utils.ts
apps/calendar/playwright/week/timeGridEventClick.e2e.ts
apps/calendar/playwright/week/timeGridEventMoving.e2e.ts
apps/calendar/playwright/week/timeGridEventResizing.e2e.ts
apps/calendar/src/components/events/timeEvent.tsx
apps/calendar/src/components/timeGrid/column.tsx
apps/calendar/src/controller/column.ts
apps/calendar/src/controller/week.ts
apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.ts
apps/calendar/src/hooks/timeGrid/useTimeGridEventResize.ts
apps/calendar/stories/mocks/mockDayViewEvents.ts
apps/calendar/stories/mocks/mockWeekViewEvents.ts
apps/calendar/stories/mocks/types.ts

- [x] It's the right issue type on the title
- Maintain the height of an event with a going or coming duration.
- Change only the end time when resizing an event with a going or coming duration.
- Set the minimum height when resizing an event with a going or coming duration.
---

fix: set proper height when moving and resizing an event with a going or coming duration

---

.github/workflows/publish-docs.yml
.github/workflows/publish-wrappers.yml
.github/workflows/test.yml
apps/calendar/examples/01-monthly-view-basic.html
apps/calendar/examples/02-monthly-view-2weeks.html
apps/calendar/examples/03-monthly-view-3weeks.html
apps/calendar/examples/04-weekly-view.html
apps/calendar/examples/05-weekly-view-no-event-view.html
apps/calendar/examples/06-daily-view.html
apps/calendar/examples/07-narrow-weekends.html
apps/calendar/examples/08-hidden-weekends.html
apps/calendar/examples/09-timezone.html
apps/calendar/examples/10-theme-common.html
apps/calendar/examples/11-theme-monthly.html
apps/calendar/examples/12-theme-weekly.html
apps/calendar/examples/13-template-monthly.html
apps/calendar/examples/14-template-weekly.html
apps/calendar/examples/15-template-popup.html
apps/calendar/examples/scripts/app.js
apps/calendar/package.json
package-lock.json
package.json
playwright.config.ts
scripts/replaceLinkInReadme.js

- Resolved #1191. (Docs are already published locally.)
- Use `node-fetch@2` for the CDN script
- Use new tags for actions, update README links
- Fixed failing CI steps
- `publish-docs`: check version inside steps, not a separated job
- `publish-wrappers`: npm token variable is wrong
---

env: fix broken CI

---

.github/workflows/publish-calendar.yml
apps/calendar/package.json
apps/calendar/playwright/day/timeGridEventMoving.e2e.ts
apps/calendar/playwright/week/timeGridEventMoving.e2e.ts
apps/calendar/playwright/week/timeGridSelection.e2e.ts
package-lock.json
package.json
playwright.config.ts

- Suppressed unexpectedly failing e2e tests only in Firefox & Safari
- Changed playwright scripts in order to test in a specific browser locally.
---

release: 2.0.3

---

.github/workflows/publish-docs.yml
apps/calendar/package.json
scripts/replaceLinkInReadme.js

- Fixed updating readme links when building core
- Tried to recover from failure after the `publish-docs` action finished
- Changed `docs:*` scripts to run `nvm` command properly
---

env: polish package build process

---

apps/calendar/package.json
package-lock.json

release: 2.0.4

---

apps/calendar/src/css/daygrid/dayGrid.css

- render only the inner border in monthly view
- AS-IS
- TO-BE
---

fix: render only inner border in monthly view

---

apps/calendar/src/components/dayGridMonth/dayGridMonth.tsx
apps/calendar/src/components/dayGridWeek/alldayGridRow.tsx
apps/calendar/src/components/timeGrid/timeGrid.tsx
apps/calendar/src/helpers/grid.spec.ts
apps/calendar/src/helpers/grid.ts

- fixed grid selection rendering when `narrowWeekend` options is true
---

fix: render grid selection properly

---

.github/workflows/publish-docs.yml
apps/calendar/package.json
package-lock.json

- Release v2.0.5
- chore: fix the `publish-docs` action because it couldn't execute post-actions
- Example: https://github.com/nhn/tui.calendar/actions/runs/2648471823
---

release: 2.0.5

---

apps/calendar/package.json
package-lock.json

release: 2.1.0

---

apps/calendar/src/store/internal.ts
apps/calendar/stories/e2e/week.stories.tsx
apps/react-calendar/docs/en/guide/getting-started.md
apps/react-calendar/docs/ko/guide/getting-started.md
apps/react-calendar/example/app.tsx
apps/react-calendar/example/theme.ts
apps/react-calendar/src/index.tsx
apps/vue-calendar/example/App.vue
apps/vue-calendar/example/app.css
apps/vue-calendar/example/mock-data.js
apps/vue-calendar/example/theme.js
apps/vue-calendar/example/utils.js
docs/en/apis/calendar.md
docs/ko/apis/calendar.md

- Improve vue-calendar and react-calendar examples.
- Fix types and options for react-calendar.
---

feat: improve vue-calendar and react-calendar examples

---

apps/calendar/playwright/week/timeGridEventClick.e2e.ts

- Fix a failed test: use Promise.all instead of await inside forEach
---

test: use Promise.all instead of await inside forEach

---

apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.ts

Fixed a weird event move behavior when the prev date or the next date has a different month and year.
---

fix: check prev & next date including month and year

---

apps/calendar/package.json
package-lock.json

release: 2.1.1

---

apps/calendar/package.json
package-lock.json

release: 2.1.2

---

apps/calendar/package.json
package-lock.json

release: 2.1.3

---

docs/en/guide/getting-started.md

* remove spaces from CDN links
---

docs: fix space issue in CDN link (fix #1272)
