src/js/handler/month/moveGuide.js
The grid line element have `tui-full-calendar-weekday-filled` class to add background color.
`MonthMoveGuide` found the grid line element when `_onDragStart`,
but those elements was removed from DOM after re-rendering the calendar while dragging.
So now `MonthMoveGuide` finds the grid line element  `_onDrag`.
---
=> fix: update background color when dragging a schedule in monthly (fix: #3)

src/js/common/vpanel.js, test/app/common/vpanel.spec.js
When the panel `options.autoHeight` is true, `setHeight()` properly set given height.
Dragging a divider to resize a panel set `isHeightForcedSet` flag. It had prevented to set height even in case of that `autoHeight` is true.
---
=> fix: resize the panel height error after dragging dvider (fix: #4)

src/js/handler/month/creation.js, test/app/handler/month/creation.spec.js
Select start time which does not over current time.
If the current time is `2018-03-08T23:38+09:00`, start time set to `2018-03-09T00:00+09:00` and end time set to `2018-03-09T01:00+09:00`.
So the day had been became next day.
(Time period is 1 hour.)
To be exact the day which is clicked, change start time to do not over current time.
For example,
if the current time is `2018-03-08T23:38+09:00`, start time set to `2018-03-08T23:30+09:00` and end time set to `2018-03-09T00:30+09:00`.
(Time period is 1 hour.)
---
=> fix: Wrong date parameter of beforeCreateSchedule callback near 24 o'click (fix #16)

src/js/handler/allday/core.js, src/js/handler/allday/resizeGuide.js, test/app/handler/allday/resizeGuide.spec.js
In narrowWeekend options, grids information(left, width) should be used to calculate the width.
---
=> fix: all-day block width is wrong when resizing it (close #43)

examples/js/data/schedules.js, src/js/controller/viewMixin/month.js, test/app/controller/viewMixin/month.spec.js
The time schedule had a top index bigger than all-day schedule. Any empty position was not used between all-day schedules.
The time schedule has a top index at empty position from the top.
---
=> fix: stack the all-day and time schedule from the top (fix #29)

src/js/common/domutil.js, src/js/handler/allday/click.js, src/js/handler/allday/creation.js, src/js/handler/allday/move.js, test/app/handler/allday/click.spec.js
no firing event when click `tui-fullcalendar-weekday-schedule-block` element.
Because it has right padding and the real clickable element is `tui-fullcalendar-weekday-schedule` which is child of `block` element.
---
=> creation failure of new all-day by clicking at right space(close #46)

src/js/factory/weekView.js
Copy panels array element  when using it.
And then `panel.showExpandableButton` set to false.
I change order of `new Week(...)` to after manipulating `panels`.
Check the scrollbar is visible and expandable button is hidden.
---
=> fix: last daygrid vpanel must has showExpandableButton=false (close #85)

src/js/view/popup/scheduleCreationPopup.js
=> fix: script error when calendar list is not set(refs: #81, #122)

src/js/view/template/popup/scheduleDetailPopup.hbs
Fix: Modify the default schedule item details popup to respect the `isreadOnly` flag in the schedule item and not display the `edit` or `delete` actions.
Feat: Modify the default schedule item details popup to not display the `location` field if it is not set.
Feat: Modify the default schedule item details popup to not display the `atendees` field if it is not set.
=> fix: Update default details popup based on schedule item flags

src/js/common/datetime.js, src/js/controller/viewMixin/week.js, src/js/model/viewModel/scheduleViewModel.js
Schedules which have no duration overlap, so I add a minimum duration to detect schedule collision. I choose 20 minutes because minimum height of schedule is about 19px when no duration. 30 minutes is about 24px. A minimun duration could be changed in the future.
---
=> fix: Schedules overlap when no duration (start == end) (close #154)

examples/js/default.js, src/js/controller/base.js, src/js/view/popup/scheduleCreationPopup.js
The location and state are updatable in the scheduleCreationPopup but are actually not saved in the updateSchedule function. 
Fix for #159 : 
- Use schedule.location instead of schedule.raw.location in scheduleCreationPopup (as defined in the model) to be consistent with the detail popup
- Save sched.location and sched.state in updateSchedule function
---
=> fix: save new location and new state during schedule update (issue 159)

examples/js/default.js, src/js/controller/viewMixin/week.js, src/js/factory/calendar.js, src/js/view/template/week/time.hbs, src/js/view/template/week/timeMoveGuide.hbs, src/js/view/week/time.js, src/js/view/week/week.js, test/app/controller/viewMixin/week.spec.js, test/app/view/time.spec.js
=> feat: Week.options.hourStart, Week.options.hourEnd (resolves: #175)

index.d.ts, package-lock.json, package.json, test/types/type-tests.ts, tslint.json
* chore: fix any type
* apply tslint
---
=> chore: fix any type

README.md, src/index.js, src/js/factory/calendar.js
This allows to disable statistics (Google Analytics) via options. The previous method via `require('tui-code-snippet.js')` still works.
Tracking information are send at the calendar constructor instead of module import. 
This is the same behaviour like e.g. [tui.image-editor](https://github.com/nhnent/tui.image-editor)
---
=> feat: disable statistics collection via options

docs/getting-started.md, src/css/month.styl, src/css/week/layout.styl
If no css height of container element, the month view and week time grid have 0px height. I add minimum height in this case. The Calendar's default height is set to 600px.
And I add the related guide.
TOAST UI Calendar's default height is 600px. If you want this calendar to fit to parent element, write container element's css like this. 
```css
#calendar {
position: absolute;
left: 0;
right: 0;
bottom: 5px;
top: 64px;
}
```
---
=> feat: support minimum height of month view

src/css/common.styl, src/js/view/template/week/time.hbs
When isReadOnly = true, it is impossible to move the schedule, and it is impossible to adjust the size.
---
=> Fix : hide resize icon with isReadOnly=true option (fix #359)

src/js/common/datetime.js, src/js/controller/base.js, src/js/controller/viewMixin/month.js, src/js/handler/time/creation.js, src/js/handler/time/creationGuide.js, test/app/handler/time/creationGuide.spec.js
*  When the user directly inputs the end time as 00:00, the schedule is drawn in the grid cell of the next day and it does not render as intended.(fix #409)
---
=> fix: If the user directly inputs the end time as 00:00, render the schedule correctly.(fix #409)

src/js/common/datetime.js, src/js/controller/base.js, src/js/controller/viewMixin/month.js, src/js/handler/time/creation.js, src/js/handler/time/creationGuide.js, test/app/handler/time/creationGuide.spec.js
* When the user directly inputs the end time as 00:00, the schedule is drawn in the grid cell of the next day and it does not render as intended.
---
=> Fix : resolve end time issue 23:25 => 00:00(next day) - for feat/dooray branch

src/js/common/datetime.js, src/js/view/week/timeGrid.js, test/app/datetime.spec.js
* If you use multiple time zones, the date difference is incorrectly displayed on the last and first day of the month.
---
=> fix: resolve incorrect diffdays on timezones area(fix #529)

examples/duplicate-schedule-layout-01.html, src/js/common/datetime.js, src/js/view/week/timeGrid.js, test/app/datetime.spec.js
* If you use multiple time zones, the date difference is incorrectly displayed on the last and first day of the month.
---
=> fix: resolve incorrect diffdays on timezones area for dooray branch(#fix Dooray-캘린더/1232)

src/js/view/template/week/time.hbs
* The resize icon should not be displayed when the schedule is `isReadOnly = true` on weekly view.(fix #470, #546 )
```js
// custom helper for 'or' operator
'or': function(a, b) {
return a || b;
},
```
When using the `or` operator, three parameters are passed and incorrect operation is performed.
```html
{{#unless (or croppedEnd @root.isReadOnly model.isReadOnly)}}
```
---
=> fix: resolve handlebars condition using 'or' custom operator(fix #546, fix #470)

src/css/variables.styl
As of https://css-tricks.com/snippets/css/clear-fix/ `zoom: 1` is necessary
for IE 6 and IE 7, but according to README.md TUI Calendar runs on IE 9+.
zoom: 1 causes warnings in Firefox.
=> Remove zoom:1 from variables.styl:clearfix()

src/js/common/domevent.js
As of https://github.com/nhn/tui.calendar#-browser-support only IE9+ is supported, so no hacks for IE before 9 are necessary.
=> IE before 9 is not supported

src/js/handler/daygrid/core.js, src/js/handler/daygrid/creation.js, src/js/handler/month/guide.js, src/js/handler/time/core.js, src/js/handler/time/creation.js, src/js/view/popup/scheduleDetailPopup.js
`util.bind(function(){…}, this)` makes no sense, as the `this` is anyway set correctly.  In particular when this is rewritten as `(function(){…}).bind(this)` eslint says this is pointless call.
In month/guide.js:this.ratio the util.bind is (at least looks so) useless, as there is no parameter to bind to.
=> Remove not needed util.bind

src/js/common/collection.js, test/app/common/collection.spec.js
=> refactor: remove unused Collection.merge()

src/css/icons.styl, src/css/popup.styl
There were two subsequent sections  `.{css-prefix}popup-detail .{css-prefix}icon`, which can be merged into a single section.
Likewise, the definitions of `.{css-prefix}dropdown-menu` and `.{css-prefix}icon.{css-prefix}ic-title` were spread over two places.
=> perf: css/popup.styl: compress two identical sections into one

src/css/variables.styl, src/js/common/common.js
=> perf: variables.styl: remove unused Taskview prefixes

src/js/view/popup/scheduleDetailPopup.js
When the body of the schedule is very long, TUI.calendar can set the top of the detail popup to be negative.  This makes reading the popup impossible, as it is not possible to scroll above the top.
With this change the top is set to be at least zero.  If the popup exceeds the viewport height, the window is enlarged and user can scroll down to read the whole popup.
=> fix#636: make sure the top of scheduleDetailPopup is non-negative

src/js/controller/base.js
=> fix the issue that updateschedule wont update isReadOnly property

src/js/factory/calendar.js
`newViewName` is set previously to "week", if it was "day".
=> Calendar.prototype.changeView: tautology

src/js/common/autoScroll.js, src/js/common/common.js, src/js/common/reqAnimFrame.js, src/js/factory/controller.js, src/js/handler/time/core.js, src/js/view/week/timeGrid.js
As of https://caniuse.com/#feat=mdn-javascript_builtins_function_bind Function.bind is supported in IE +9, Edge +12 , Firefox +4, Chrome +7, Safari +5.1.
ScheduleCreationPopup._onClickListeners() uses Function.bind since April 2018, and TimeCreationGuide._onDrag uses it since Mai 2017, so the aforementioned browser versions are required that long.
• Replace util.bind(x,y) with x.bind(y)
• Update README.md with the minimal supported versions.
=> Substitute util.bind with Function.bind

src/js/model/schedule.js
=> fix: always consider timezone when set allday schedule period(fix #662)

src/js/common/datetime.js, src/js/controller/viewMixin/core.js, src/js/controller/viewMixin/month.js, src/js/controller/viewMixin/week.js, src/js/handler/month/core.js, src/js/view/popup/scheduleCreationPopup.js, test/app/handler/month/core.spec.js
* fix: When the end time of the schedule is resized to the previous date in the monthly view, the schedule size rendered is restored (#646 **issue1**)
| AS-IS | TO-BE |
| --- | --- |
| ![tui-calendar-issue-646-1](https://user-images.githubusercontent.com/43128697/86193926-1de95a00-bb88-11ea-8966-2fbe10f70bfe.gif) | ![tui-calendar-issue-646-1-tobe](https://user-images.githubusercontent.com/43128697/86193947-2772c200-bb88-11ea-8564-2941097dfeed.gif) |
* fix : resolve midnight schedule on monthly view(#646 **issue2**)
| AS-IS | TO-BE |
| --- | --- |
| <img width="206" alt="스크린샷 2020-07-01 10 48 35" src="https://user-images.githubusercontent.com/43128697/86194111-9b14cf00-bb88-11ea-9dbd-6616ad685c88.png"> | <img width="479" alt="스크린샷 2020-07-01 10 49 19" …
=> fix: resolve schedule rendering issues on month view (#646)

docs/getting-started.md
Fixed key typo of `header` field to `height`, since `IMonthOptions.grid?` should implements `header?: { height?: number }`
https://github.com/nhn/tui.calendar/blob/a1d5e1c8df8184eec0f8a7c52ad6fe97b2a130ce/index.d.ts#L162
=> docs: fix typo in getting-started.md

src/js/view/popup/scheduleCreationPopup.js
* When creating a calendar instance using the default creation popup, if the [`CalendarProps`](https://nhn.github.io/tui.calendar/latest/CalendarProps) have an id with the `number type, then the selected calendar id cannot be found.
* This comes from the wrong implementation when finding a selected calendar.
* `domutil.getData` returns always the string type.
* [If a selected calendar is missing, the popup passes just `null`.](https://github.com/nhn/tui.calendar/blob/master/src/js/view/popup/scheduleCreationPopup.js#L275)
* So this PR makes the popup find the selected calendar no matter what type of calendar id.
---
=> fix: treat `calendarId` as string type when finding selected calendar (fix #851)

src/js/common/model.js, src/js/common/point.js, src/js/common/timezone.js, src/js/handler/month/guide.js, src/js/view/popup/scheduleCreationPopup.js, src/js/view/popup/scheduleDetailPopup.js
There are small typos in:
- src/js/common/model.js
- src/js/common/point.js
- src/js/common/timezone.js
- src/js/handler/month/guide.js
- src/js/view/popup/scheduleCreationPopup.js
- src/js/view/popup/scheduleDetailPopup.js
Fixes:
- Should read `coordinates` rather than `coodinates`.
- Should read `timestamp` rather than `timestampe`.
- Should read `custom` rather than `custome`.
- Should read `sequential` rather than `sequencial`.
- Should read `appear` rather than `apear`.
- Should read `trimmed` rather than `trimed`.
- Should read `limitation` rather than `limitaion`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

examples/js/app.js, examples/js/data/schedules.js, src/js/controller/base.js, src/js/view/popup/scheduleCreationPopup.js, src/js/view/week/dayGrid.js, test/app/view/scheduleCreationPopup.spec.js
- Changed wrong JSDoc comment (#930)
- Fixed wrong usage of the `raw` property in the `Schedule` model. (#927)
- The `raw` property is only for library consumers who want to save arbitrary data in the `Schedule` instance.
- There is already `isPrivate` in the `Schedule` model. so replace logic to use it.
- Also example code has been changed not to use `raw` properties inappropriately.
---
=> fix: wrong private schedule assignment in default popup (resolve #927)

src/js/factory/calendar.js
* `TimeGrid` relies on deprecated `timezones` property yet. So synchronize it.
* Reference: https://github.com/nhn/tui.calendar/blob/248131a10c333b2cbae89adc2e7f1c7db5a68cd1/src/js/factory/calendar.js#L726
---
=> fix: update timezones property when calling `setOptions` method (fix #967)

src/js/controller/base.js, test/app/controller/base.spec.js
- This PR applies the `recurrenceRule` changes in the `updateSchedule` method.
---
=> fix: apply `recurrenceRule` changes (fix #936)

apps/calendar/index.d.ts, apps/calendar/playwright/day/timeGridEventMoving.e2e.ts, apps/calendar/src/components/panel.tsx, apps/calendar/src/components/view/day.spec.tsx, apps/calendar/src/components/view/day.tsx, apps/calendar/src/components/view/week.spec.tsx, apps/calendar/src/components/view/week.tsx, apps/calendar/src/constants/layout.ts, apps/calendar/src/constants/view.ts, apps/calendar/src/factory/calendarControl.tsx, apps/calendar/src/helpers/view.ts, apps/calendar/src/slices/layout.ts, apps/calendar/src/slices/options.ts, apps/calendar/types/options.d.ts, playwright.config.ts
* [BREAKING CHANGE] `scheduleView` and `taskView` options are deprecated.
* Instead, use `week.eventView` and `week.taskView`.
```js
const options = {
// scheduleView: true, // deprecated
// taskView: true, // deprecated
week: {
eventView: true, // set by a boolean value
taskView: ['milestone', 'task'] // or array
}
};
```
* The default values of `week.eventView` and `week.taskView` are `true`.
* Implement `week.eventView` and `week.taskView`.
* When the options are `{ week: { eventView: ['allday'], taskView: ['task'] } }`
* ![image](https://user-images.githubusercontent.com/8615506/165203313-5394f3fb-f728-46e6-a0a8-7c5344ddfcf5.png)
---
=> feat: implement week.eventView and week.taskView options

apps/calendar/index.d.ts, apps/calendar/src/components/dayGridMonth/dayGridMonth.tsx, apps/calendar/src/components/view/day.tsx, apps/calendar/src/components/view/month.spec.tsx, apps/calendar/src/components/view/month.tsx, apps/calendar/src/components/view/week.spec.tsx, apps/calendar/src/components/view/week.tsx, apps/calendar/src/helpers/events.ts, apps/calendar/src/helpers/view.ts, apps/calendar/src/hooks/calendar/useCalendarData.ts, apps/calendar/src/slices/options.ts, apps/calendar/stories/dayGridMonth.stories.tsx, apps/calendar/types/options.d.ts
* [BREAKING CHANGE] `month.eventFilter` option is deprecated.
* Instead, use `eventFilter`.
```js
const options = {
// month: { eventFilter: (event) => event.isVisible }, // deprecated
eventFilter: (event) => event.isVisible
};
```
* The default value is `(event: EventModelData) => !!(event.isVisible && ['allday', 'time'].includes(event.category || ''));`.
* If the `eventFilter` option is specified, original event filter is overwritten.
* Implement the `eventFilter` option.
---
=> feat: implement eventFilter option

apps/calendar/src/components/events/horizontalEvent.spec.tsx, apps/calendar/src/components/events/horizontalEvent.tsx, apps/calendar/src/components/events/timeEvent.spec.tsx, apps/calendar/src/components/events/timeEvent.tsx, apps/calendar/src/test/utils.tsx, apps/calendar/types/eventBus.d.ts
- Fire `afterRenderEvent` when event components are mounted.
- This really doesn't need to disable the ESLint rule, but just in case.
---
=> feat: implement `afterRenderEvent` instance event

apps/calendar/src/components/view/day.tsx, apps/calendar/src/components/view/week.tsx, apps/calendar/src/hooks/timeGrid/useTimezoneLabelsTop.ts, apps/calendar/stories/e2e/day.stories.tsx
* Set TimezoneLabels top position to TimePanel's offsetTop
* before
* ![image](https://user-images.githubusercontent.com/8615506/172580519-2aaa7c62-cd3a-4bb0-9d3e-a083611b1fda.png)
* after
* ![image](https://user-images.githubusercontent.com/8615506/172580775-16577356-5530-427b-823a-f9801e224ba0.png)
* Implement TimezoneLabels in the day view
---
=> fix: set TimezoneLabels' top position correctly and implement TimezoneLabels in the day view

.github/workflows/publish-docs.yml
The current `publish-docs` action fails due to calling `rm -rf` inside the working directory. This PR addresses this problem.
---
=> fix: avoid calling `rm -rf` to remove parent directory

apps/calendar/src/components/events/horizontalEvent.tsx
- Apply `border-radius` only on the first and last date of a horizontal event.
---
=> fix: apply border-radius only on the first and last date of a horizontal event

.github/workflows/publish-calendar.yml, apps/calendar/package.json, package-lock.json
- Release `calendar@2.0.2`
- Use new tag naming
=> release: 2.0.2

apps/calendar/src/time/timezone.ts
* this variable was introduced for SSR, but it's not useful at all.
* also, it breaks the ESM bundle when it's not defined as `window`.
---
=> fix: remove unnecessary `global` variable

apps/calendar/playwright/week/timeGridEventResizing.e2e.ts, apps/calendar/src/controller/column.ts
- calibrate short event with going, coming duration
- AS-IS (30 minutes event with going, coming duration)
- TO-BE
---
=> fix: calibrate 30minutes event height

.eslintrc.js, apps/calendar/src/helpers/grid.spec.ts, apps/calendar/src/helpers/grid.ts
- fixed calculation of `getWeekDates` correctly
- today: `Friday`, `startDayOfWeek`: `6(Saturday)`
- AS-IS
- TO-BE
This issue resolves #1198.
---
=> fix: getWeekDates calculate week dates correctly

apps/calendar/src/components/events/horizontalEvent.spec.tsx, apps/calendar/src/components/events/horizontalEvent.tsx, apps/calendar/src/components/events/timeEvent.spec.tsx, apps/calendar/src/components/events/timeEvent.tsx
- This issue resolves #1216.
- The `clickEvent` event should be fired only when clicked.
---
=> fix: prevent firing `clickEvent` when dragging events (fix #1216)

apps/calendar/src/components/view/day.tsx, apps/calendar/src/components/view/week.tsx, apps/calendar/src/factory/week.spec.tsx, apps/calendar/src/helpers/grid.ts, apps/calendar/src/time/datetime.ts, apps/calendar/src/time/timezone.ts, apps/calendar/stories/e2e/week.stories.tsx, apps/calendar/stories/gridRow.stories.tsx
* Renamed `getDayGridEvents` to `getWeekViewEvents`
* `getWeekViewEvents` calculates the start of the week and end of the week from the given array. But this implementation filters some events when the timezone option is enabled.
* because the original start & end time of the filtered event might be in the previous or next week before applying the timezone offset.
* So when calling `getWeekViewEvents`, adjust the start and the end of the filter range by the timezone.
---
=> fix: adjust start of week and end of week by timezone

apps/calendar/src/time/datetime.ts
I am using a calendar week view with 4 weeks of events in one long row. For this I needed to increase WEEK_DAYS. However, I found out that in this line of code the number of days per week is still hardcoded instead of relying on the WEEK_DAYS constant.
---
=> refactor: Replace 7 by WEEK_DAYS

apps/calendar/src/components/popup/eventFormPopup.spec.tsx, apps/calendar/src/components/popup/eventFormPopup.tsx, apps/calendar/src/components/popup/locationInputBox.tsx, apps/calendar/src/components/popup/titleInputBox.tsx, apps/calendar/src/hooks/popup/useFormState.ts
- Synced form state with input components
- Some of `formState` was irrelevant to the popup. So it was removed.
- Reset form states when closing the popup
Resolves #1233 
https://user-images.githubusercontent.com/14539203/182062782-71c66a43-82f3-4fd6-900c-69ab6085d9d3.mov
https://user-images.githubusercontent.com/14539203/182062796-e43d890d-6bf3-46a6-8005-9c9390d69e06.mov
---
=> fix: sync form state with inputs (fix #1233)

.eslintrc.js, apps/calendar/playwright/assertions.ts, apps/calendar/playwright/configs.ts, apps/calendar/playwright/day/timeGridSelection.e2e.ts, apps/calendar/playwright/week/timeGridSelection.e2e.ts, apps/calendar/src/components/timeGrid/gridSelectionByColumn.tsx, apps/calendar/src/helpers/gridSelection.ts
This PR resolves #1238 and #1239.
---
=> fix: calculate endRowIndex properly when `week.hourStart/hourEnd` option is applied (fix #1238)

apps/calendar/src/components/popup/eventDetailPopup.spec.tsx, apps/calendar/src/components/popup/eventDetailPopup.tsx, docs/en/apis/calendar.md, docs/ko/apis/calendar.md
Fixed that the default form popup appears even though the `useFormPopup` option is disabled. because the `EventDetailPopup` component is calling it ignoring the option.
Resolves #1249.
https://user-images.githubusercontent.com/14539203/184304857-48194610-3b46-4653-a74a-f62d3346d630.mov
https://user-images.githubusercontent.com/14539203/184304932-71acfbe8-4aef-4546-a78c-7ed82f290837.mov
---
=> fix: prevent opening form popup through detail popup when it is disabled

apps/calendar/src/components/events/horizontalEvent.spec.tsx, apps/calendar/src/components/events/horizontalEvent.tsx
- afterRenderEvent works in readonly mode
- add test in this feature 
Resolves #1327 
---
=> fix: afterRenderEvent doesn't work in readonly mode ( fix #1327 )
